# Generated by Django 5.0.6 on 2024-05-22 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoginUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=32)),
                ('Password', models.CharField(max_length=230)),
                ('is_admin', models.BooleanField(default=False)),
                ('created_by', models.CharField(blank=True, max_length=32, null=True)),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(blank=True, max_length=32, null=True)),
                ('modified_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'loginuser',
            },
        ),
    ]
